"""
    This file contains constants used throughout this project.
"""
# Units
LENGTH_UNIT = "m"
MICRO_LENGTH_UNIT = "mm"
TIME_UNIT = "s"
MICRO_TIME_UNIT = "ms"
MASS_UNIT = "kg"
VOLUME_UNIT = "ul"

# Headers for excel file sheets
FILENAME_HEADER = "Filename"
WEBER_NO_JET_HEADER = "We_jet"
WEBER_NO_LOCAL_HEADER = "We_local"

BREAKUP_JET_VELOCITY_MS_HEADER = f"Jet Exit Velocity at Breakup ({LENGTH_UNIT}/{TIME_UNIT})"
BREAKUP_LOCAL_VELOCITY_MS_HEADER = f"Local Velocity at Breakup ({LENGTH_UNIT}/{TIME_UNIT})"
SIDE_BREAKUP_INDEX_HEADER = "Side Breakup Index"
TOP_BREAKUP_INDEX_HEADER = "Top Breakup Index"
BREAKUP_INDEX_HEADER = "Breakup Index"
LENGTH_HEADER = f"Length ({MICRO_LENGTH_UNIT})"
HEIGHT_HEADER = f"Height ({MICRO_LENGTH_UNIT})"
WIDTH_HEADER = f"Width ({MICRO_LENGTH_UNIT})"
VOLUME_HEADER = f"Volume ({VOLUME_UNIT})"
LEFT_CONTACT_ANGLE_HEADER = "Left CA"
RIGHT_CONTACT_ANGLE_HEADER = "Right CA"
AVG_CONTACT_ANGLE_HEADER = "Average CA"
CAH_HEADER = "CAH"
DIAMETER_HEADER = f"Diameter ({MICRO_LENGTH_UNIT})"
TOP_AREA_HEADER = f"Wetted Area ({MICRO_LENGTH_UNIT}^2)"
ANTICIRCULARITY_HEADER = "Anti-circularity"
X_POSITION_HEADER = f"X position ({MICRO_LENGTH_UNIT})"
Y_POSITION_HEADER = f"Y position ({MICRO_LENGTH_UNIT})"
ERROR_HEADER = "Error"
W_MIN_HEADER = f"Min Width ({MICRO_LENGTH_UNIT})"
TIME_HEADER = f"Time ({MICRO_TIME_UNIT})"

NORMALIZED_HEADER_SUFFIX = "NORMALIZED"

# Labels used in excel file (e.g. plots labels)
JET_EXIT_VELOCITY_LABEL = "Jet Exit Velocity"
LEFT_DISPLACEMENT_LABEL = "Left Displacement"
RIGHT_DISPLACEMENT_LABEL = "Right Displacement"
HEIGHT_LABEL = "Height"
WIDTH_LABEL = "Width"
LENGTH_LABEL = "Length"
POINT_ANALYSIS_LABEL = "Point Analysis"

STAT_LABEL = "Stat"
AVERAGE_LABEL = "Average"
STD_LABEL = "STD"
MODE_LABEL = "Mode"
MEDIAN_LABEL = "Median"
PERCENTILE_25_LABEL = "25th Percentile"
PERCENTILE_75_LABEL = "75th Percentile"
NORMALIZED_LABEL = "Normalized"

SLOPE_LABEL = "slope"
INTERCEPT_LABEL = "intercept"

# Filenames
EXCEL_FILE_EXTENSION = ".xlsx"
DAVIS_SET_FILE_EXTENSION = ".set"
PNG_FILE_EXTENSION = ".png"
EPS_FILE_EXTENSION = ".eps"
BREAKUP_DETECTOR_EXCEL_FILENAME = f"Breakup Detection{EXCEL_FILE_EXTENSION}"
NECKING_DETECTOR_EXCEL_FILENAME = f"Necking Detection{EXCEL_FILE_EXTENSION}"
COLLATER_EXCEL_FILENAME = f"Cumulative{EXCEL_FILE_EXTENSION}"
CHILD_DROPLET_MEASUREMENT_EXCEL_FILENAME = f"Child Droplet Measurements{EXCEL_FILE_EXTENSION}"
INITIAL_CONDITIONS_EXCEL_FILENAME = f"Initial Conditions{EXCEL_FILE_EXTENSION}"
WIDTH_DISTRIBUTION_EXCEL_FILENAME = f"Width Distribution{EXCEL_FILE_EXTENSION}"

# Folder names
BREAKUP_DETECTOR_IMAGES_FOLDERNAME = "Breakup Plots"
NECKING_DETECTOR_IMAGES_FOLDERNAME = "Necking Plots"
INITIAL_CONDITIONS_IMAGES_FOLDERNAME = "Initial Condition Plots"

# Excel sheet names
BREAKUP_STATISTICS_SHEETNAME = "Breakup Stats"
STATISTICS_SHEETNAME = "Statistics"
BREAKUP_DETECTOR_DATA_SHEETNAME = "Breakup Data"
NECKING_DETECTOR_DATA_SHEETNAME = "Necking Data"
FILTERED_DATA_SHEETNAME = "Filtered Data"
DATA_SHEETNAME = "Data"
EXCEL_DEFAULT_SHEETNAME = "Sheet"
TESTS_SHEETNAME = "Tests"
SESSILE_SHEETNAME = "Sessile"
DEPINNING_SHEETNAME = "Depinning"
BREAKUP_SHEETNAME = "Breakup"
CHILD_DROPLET_SHEETNAME = "Child Droplet"
VOLUME_SHEETNAME = "Volume"
MIN_WIDTH_SHEETNAME = "Min Width"

# Experiment conditions
ACQUISITION_PERIOD = 8 # ms
ACQUISITION_FREQUENCY = 120 # Hz
SIDE_IMAGE_RESOLUTION = 28.27
TOP_IMAGE_RESOLUTION = 29.32
SIDE_IMAGE_SCALE = 1 / SIDE_IMAGE_RESOLUTION
TOP_IMAGE_SCALE = 1 / TOP_IMAGE_RESOLUTION
AIR_DENSITY = 1.2  # kg/m^3
DROPLET_DENSITY = 0.072  # N/m
WEBER_NO_SUFFIX = AIR_DENSITY / DROPLET_DENSITY  # We = WEBER_NO_SUFFIX * (U * D)
FLOW_RAMP_FITLINES = {
    4.4: {
        SLOPE_LABEL: 4.7303408085,
        INTERCEPT_LABEL: -1.6190716868
    },
    3.2: {
        SLOPE_LABEL: 3.4542,
        INTERCEPT_LABEL: -1.3055
    },
    2.2: {
        SLOPE_LABEL: 2.3498,
        INTERCEPT_LABEL: -1.0454
    },
    1.2: {
        SLOPE_LABEL: 1.2631,
        INTERCEPT_LABEL: -0.7672
    }
}

# Excel constants
NAN_FROM_EXCEL = "#N/A"
ALT_NAN_FROM_EXCEL = "=NA()"
ERROR_FROM_EXCEL = "#VALUE!"
REF_VALUE_FROM_EXCEL = "#REF!"
DIV0_EXCEL_ERROR = "#DIV/0!"
ERROR_VALUE_FOR_INPUT = "NA()"
EXCEL_ERROR_VALUES = [
    NAN_FROM_EXCEL,
    ALT_NAN_FROM_EXCEL,
    ERROR_FROM_EXCEL,
    REF_VALUE_FROM_EXCEL,
    ERROR_VALUE_FOR_INPUT,
    DIV0_EXCEL_ERROR
]

# plotter.py constants
HEADER_HEADER, X_HEADER, Y_HEADER = "header", "x", "y"
Y_ERROR_HEADER, Y_POS_ERROR_HEADER, Y_NEG_ERROR_HEADER = "yerror", "yerror+", "yerror-"
X_ERROR_HEADER, X_POS_ERROR_HEADER, X_NEG_ERROR_HEADER = "xerror", "xerror+", "xerror-"
INDEX_HEADER = 'index'
SECONDARY_SERIES_PREFIX = 'secondary_'
SECONDARY_2_SERIES_PREFIX = 'secondary2_'
SECONDARY_3_SERIES_PREFIX = 'secondary3_'
